/*=============================================================================
   Copyright (c) 2014-2022 Cycfi Research. All rights reserved.

   Distributed under the MIT License [ https://opensource.org/licenses/MIT ]
=============================================================================*/
#if !defined(CYCFI_INFINITY_DRIVER_H_JULY_25_2022)
#define CYCFI_INFINITY_DRIVER_H_JULY_25_2022

// Note: This file is included from source files autogenerated by CubeMX

#if !defined(INFINITY_ADC_BUFFER_SIZE)
#define INFINITY_ADC_BUFFER_SIZE (INFINITY_NUM_SAMPLES * INFINITY_NUM_CHANNELS)
#endif

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

// Main setup and loop
void setup();
void loop();

// Timer interrupt
void timer3_interrupt();

// DAC 1 and 2 out
void dac1_out(uint16_t sample);
void dac2_out(uint16_t sample);

// ADC callbacks
void adc_in_half(uint16_t* samples, size_t size);
void adc_in_full(uint16_t* samples, size_t size);

// USB CDC transmit
uint8_t CDC_transmit(uint8_t* buff, uint16_t Len);

// SPI functions

// Non-blocking transmit functions
void spia_transmit(uint8_t* data, uint16_t size);
void spia_transmit_complete(); // Transmit callback

// Non-blocking receive functions
void spia_receive(uint8_t* data, uint16_t size);
void spia_receive_complete(); // Receive callback

// Non-blocking send receive functions
void spia_transmit_receive(uint8_t* tx_data, uint8_t* rx_data, uint16_t size);
void spia_transmit_receive_complete(); // Send receive callback

// GPIO Interrupt
void gpio_interrupt(int pin);

#ifdef __cplusplus
}
#endif

#endif
