/*=============================================================================
   Copyright (c) 2014-2023 Cycfi Research. All rights reserved.

   Distributed under the MIT License [ https://opensource.org/licenses/MIT ]
=============================================================================*/
#if !defined(CYCFI_INFINITY_DRIVER_H_JULY_25_2022)
#define CYCFI_INFINITY_DRIVER_H_JULY_25_2022

// Note: This file is included from source files autogenerated by CubeMX

#if defined(INFINITY_HAS_ADC) && !defined(INFINITY_ADC_BUFFER_SIZE) && defined(INFINITY_NUM_SAMPLES) && defined(INFINITY_NUM_CHANNELS)
#define INFINITY_ADC_BUFFER_SIZE (INFINITY_NUM_SAMPLES * INFINITY_NUM_CHANNELS)
#endif

#if defined(INFINITY_HAS_ADC1) && !defined(INFINITY_ADC1_BUFFER_SIZE) && defined(INFINITY_ADC1_NUM_SAMPLES) && defined(INFINITY_ADC1_NUM_CHANNELS)
#define INFINITY_ADC1_BUFFER_SIZE (INFINITY_ADC1_NUM_SAMPLES * INFINITY_ADC1_NUM_CHANNELS)
#endif

#if defined(INFINITY_HAS_ADC2) && !defined(INFINITY_ADC2_BUFFER_SIZE) && defined(INFINITY_ADC2_NUM_SAMPLES) && defined(INFINITY_ADC2_NUM_CHANNELS)
#define INFINITY_ADC2_BUFFER_SIZE (INFINITY_ADC2_NUM_SAMPLES * INFINITY_ADC2_NUM_CHANNELS)
#endif

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

// Main setup and loop
void setup();
void loop();

// Timer interrupts
#if defined(INFINITY_HAS_TIMER2)
void timer2_interrupt();
#endif

#if defined(INFINITY_HAS_TIMER3)
void timer3_interrupt();
#endif

// DAC 1 and 2 out
#if defined(INFINITY_HAS_DAC)
void dac1_out(uint16_t sample);
void dac2_out(uint16_t sample);
#endif

// ADC callbacks
#if defined(INFINITY_HAS_ADC)
void adc_in_half(volatile uint16_t* samples, size_t size);
void adc_in_full(volatile uint16_t* samples, size_t size);
#endif

#if defined(INFINITY_HAS_ADC1)
void adc1_in_half(volatile uint16_t* samples, size_t size);
void adc1_in_full(volatile uint16_t* samples, size_t size);
#endif

#if defined(INFINITY_HAS_ADC2)
void adc2_in_half(volatile uint16_t* samples, size_t size);
void adc2_in_full(volatile uint16_t* samples, size_t size);
#endif

// USB CDC transmit
#if defined(INFINITY_HAS_USB_CDC)
uint8_t CDC_transmit(uint8_t* buff, uint16_t Len);
#endif

// SPI functions

#if defined(INFINITY_HAS_SPIA)
// Non-blocking transmit functions
void spia_transmit(uint8_t* data, uint16_t size);
void spia_transmit_complete(); // Transmit callback

// Non-blocking receive functions
void spia_receive(uint8_t* data, uint16_t size);
void spia_receive_complete(); // Receive callback

// Non-blocking send receive functions
void spia_transmit_receive(uint8_t* tx_data, uint8_t* rx_data, uint16_t size);
void spia_transmit_receive_complete(); // Send receive callback
#endif

// GPIO Interrupt
#if defined(INFINITY_HAS_GPIO_INTERRUPT)
void gpio_interrupt(int pin);
#endif

#ifdef __cplusplus
}
#endif

#endif
