/*=============================================================================
   Copyright (c) 2014-2023 Cycfi Research. All rights reserved.

   Distributed under the MIT License [ https://opensource.org/licenses/MIT ]
=============================================================================*/
// Umbrella C interface for the stm32_driver barrier. Included from the
// CubeMX-autogenerated Core sources so a single include exposes every hook
// and prototype. The real declarations live in the focused per-subsystem
// headers below; each self-guards on its INFINITY_HAS_* feature macro, so
// including them all is safe on any board. Application C++ code includes the
// matching `.hpp` facades, not this file.
#if !defined(CYCFI_INFINITY_DRIVER_H_JULY_25_2022)
#define CYCFI_INFINITY_DRIVER_H_JULY_25_2022

// Note: This file is included from source files autogenerated by CubeMX

#include <stdint.h>
#include <stddef.h>

#include <inf/detail/main.h>          // setup / loop
#include <inf/detail/adc.h>           // DMA input hooks + polled scan + macros
#include <inf/detail/dac.h>           // dac1/2_out
#include <inf/detail/spi.h>           // spia_* transfers + completion hooks
#include <inf/detail/i2c_master.h>    // i2c_master_* (master + register access)
#include <inf/detail/i2c_slave.h>     // i2c_slave_* (raw + register-file service)
#include <inf/detail/cdc.h>           // USB CDC transmit + eth_cdc_rx hook
#include <inf/detail/timer.h>         // timer2/3_interrupt hooks
#include <inf/detail/gpio.h>          // gpio_interrupt hook

#endif
